# These are supported funding model platforms

<<<<<<< HEAD
github: nunomaduro
patreon: nunomaduro
custom: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=66BYDWAT92N6L
=======
github: fleetbase
>>>>>>> fc80cb8 (latest)
